{
 "title": "EthiQuest Program Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ProjectID", "query": "SELECT id\nFROM projects" }
  ]
 },
 "panels": [
  { "title": "Program Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ProjectID" },
  {
   "title": "Program Description",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "flow_camp_db",
     "rawSql": "SELECT Name, Description FROM flow_camp_db.Projects WHERE id = $ProjectID LIMIT 50 "
    },
    {
     "dataset": "flow_camp_db",
     "rawSql": "SELECT Name, ExpectedROI FROM flow_camp_db.Projects WHERE id = $ProjectID LIMIT 50 "
    }
   ]
  },
  {
   "title": "Stakeholders",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "flow_camp_db",
     "rawSql": "SELECT Name,  FROM flow_camp_db.Stakeholders LIMIT 50 "
    }
   ]
  },
  {
   "title": "Key Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "flow_camp_db",
     "rawSql": "SELECT Budget, ExpectedROI, CostSavings FROM flow_camp_db.Projects LIMIT 50 "
    }
   ]
  },
  {
   "title": "Risks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 10 },
   "targets": [
    {
     "dataset": "flow_camp_db",
     "rawSql": "SELECT PotentialEvent, PotentialImpact, id FROM flow_camp_db.Risks LIMIT 50 "
    }
   ]
  }
 ]
}