"""Initial migration

Revision ID: 7ad44f8f19ca
Revises: 
Create Date: 2023-10-08 19:42:22.368933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ad44f8f19ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dilemmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('question', sa.String(length=500), nullable=True))
        batch_op.drop_column('ID')
        batch_op.drop_column('Question')

    with op.batch_alter_table('Options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('text', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pros', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cons', sa.String(length=500), nullable=True))
        batch_op.alter_column('DilemmaID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('Options_DilemmaID_Dilemmas_ID', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Dilemmas', ['DilemmaID'], ['id'])
        batch_op.drop_column('ID')
        batch_op.drop_column('Pros')
        batch_op.drop_column('Cons')
        batch_op.drop_column('Text')

    with op.batch_alter_table('UserChoices', schema=None) as batch_op:
        batch_op.drop_constraint('UserChoices_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('UserChoices_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Dilemmas', ['DilemmaID'], ['id'])
        batch_op.create_foreign_key(None, 'Options', ['OptionID'], ['id'])

    with op.batch_alter_table('ViewedDilemmas', schema=None) as batch_op:
        batch_op.drop_constraint('ViewedDilemmas_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Dilemmas', ['dilemma_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ViewedDilemmas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ViewedDilemmas_ibfk_1', 'Dilemmas', ['dilemma_id'], ['ID'])

    with op.batch_alter_table('UserChoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('UserChoices_ibfk_2', 'Options', ['OptionID'], ['ID'])
        batch_op.create_foreign_key('UserChoices_ibfk_1', 'Dilemmas', ['DilemmaID'], ['ID'])

    with op.batch_alter_table('Options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Text', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('Cons', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('Pros', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Options_DilemmaID_Dilemmas_ID', 'Dilemmas', ['DilemmaID'], ['ID'])
        batch_op.alter_column('DilemmaID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('cons')
        batch_op.drop_column('pros')
        batch_op.drop_column('text')
        batch_op.drop_column('id')

    with op.batch_alter_table('Dilemmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Question', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('question')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
